# Generated by Selenium IDE
from lib2to3.pgen2 import driver
from selenium import webdriver
import time  
print("test case started")  

class TestSamp():
    driver = webdriver.Chrome(executable_path= 'C:\\Program Files\\Selenium\\chromedriver.exe')
    print("entered chrome driver")
    driver.maximize_window()  
    driver.delete_all_cookies()  
    driver.get("https://www.facebook.com/") 
    # driver.find_element_by_xpath("//*[@id='identifierId']").click()  
    driver.find_element("xpath", "//*[@id='email']").click()
    driver.find_element("xpath", "//*[@id='email']").send_keys("devaki1906")  
    driver.find_element("xpath","//*[@id='pass']").click()
    driver.find_element("xpath","//*[@id='pass']").send_keys("8270719068")  
    time.sleep(3)
    driver.find_element("name","login").click()  
    time.sleep(3)  
    driver.close()  
    print("Facebook should not login")    
    
  
